import { MarketplaceItem } from './marketplace.types';

export const MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: 'book-hardcover-signature',
    title: 'Hardcover Signature Book',
    category: 'Books',
    shortDescription: 'Premium casebound book for portfolios, annual reports, and high-end catalogs.',
    priceFrom: 38,
    rating: 4.8,
    reviewsCount: 312,
    tags: ['Bestseller', 'Premium', 'Fast shipping'],
    isAvailable: true,
  },
  {
    id: 'book-softcover-starter',
    title: 'Softcover Starter Book',
    category: 'Books',
    shortDescription: 'Lightweight perfect-bound format for handouts, guides, and manuals.',
    priceFrom: 18,
    rating: 4.5,
    reviewsCount: 184,
    tags: ['Most popular', 'Bulk discount', 'Eco'],
    isAvailable: true,
  },
  {
    id: 'book-layflat-photo',
    title: 'Layflat Photo Book',
    category: 'Books',
    shortDescription: 'Layflat pages designed for uninterrupted full-spread photo storytelling.',
    priceFrom: 46,
    rating: 4.9,
    reviewsCount: 206,
    tags: ['Premium', 'New'],
    isAvailable: true,
  },
  {
    id: 'book-notebook-journal',
    title: 'Branded Journal Notebook',
    category: 'Books',
    shortDescription: 'Custom branded journals with durable covers and smooth writing paper.',
    priceFrom: 16,
    rating: 4.4,
    reviewsCount: 97,
    tags: ['Eco', 'Fast shipping'],
    isAvailable: true,
  },
  {
    id: 'book-annual-report',
    title: 'Annual Report Book',
    category: 'Books',
    shortDescription: 'Corporate-grade report books with precise color and professional finishing.',
    priceFrom: 52,
    rating: 4.7,
    reviewsCount: 142,
    tags: ['Premium', 'Matte finish'],
    isAvailable: true,
  },
  {
    id: 'book-lookbook-premium',
    title: 'Premium Brand Lookbook',
    category: 'Books',
    shortDescription: 'Fashion and product lookbooks with rich blacks and crisp typography.',
    priceFrom: 49,
    rating: 4.8,
    reviewsCount: 129,
    tags: ['Bestseller', 'Gloss finish'],
    isAvailable: false,
  },
  {
    id: 'book-story-children',
    title: 'Children Story Book',
    category: 'Books',
    shortDescription: 'Colorful short-run story books for schools, libraries, and family projects.',
    priceFrom: 24,
    rating: 4.6,
    reviewsCount: 88,
    tags: ['New', 'Eco'],
    isAvailable: true,
  },
  {
    id: 'book-portfolio-artist',
    title: 'Artist Portfolio Book',
    category: 'Books',
    shortDescription: 'Portfolio-ready print quality for illustration, design, and architecture work.',
    priceFrom: 44,
    rating: 4.9,
    reviewsCount: 167,
    tags: ['Premium', 'Fast shipping'],
    isAvailable: true,
  },
  {
    id: 'calendar-wall-classic',
    title: 'Classic Wall Calendar',
    category: 'Calendars',
    shortDescription: 'A practical monthly wall calendar with bold grid layout and custom branding.',
    priceFrom: 12,
    rating: 4.5,
    reviewsCount: 251,
    tags: ['Bestseller', 'Bulk discount'],
    isAvailable: true,
  },
  {
    id: 'calendar-desk-spiral',
    title: 'Spiral Desk Calendar',
    category: 'Calendars',
    shortDescription: 'Compact desk format for offices and customer gifting campaigns.',
    priceFrom: 14,
    rating: 4.4,
    reviewsCount: 173,
    tags: ['Most popular', 'Fast shipping'],
    isAvailable: true,
  },
  {
    id: 'calendar-magnetic-family',
    title: 'Magnetic Family Calendar',
    category: 'Calendars',
    shortDescription: 'Magnetic fridge calendar with durable print and writable date blocks.',
    priceFrom: 17,
    rating: 4.3,
    reviewsCount: 61,
    tags: ['New', 'Eco'],
    isAvailable: true,
  },
  {
    id: 'calendar-weekly-planner',
    title: 'Weekly Planner Calendar',
    category: 'Calendars',
    shortDescription: 'Weekly planning layout for teams that need line-level scheduling detail.',
    priceFrom: 19,
    rating: 4.2,
    reviewsCount: 54,
    tags: ['Matte finish', 'Bulk discount'],
    isAvailable: true,
  },
  {
    id: 'calendar-pocket-mini',
    title: 'Mini Pocket Calendar',
    category: 'Calendars',
    shortDescription: 'Small-format portable calendars for direct mail and campaign inserts.',
    priceFrom: 9,
    rating: 4.1,
    reviewsCount: 39,
    tags: ['Fast shipping', 'Eco'],
    isAvailable: false,
  },
  {
    id: 'poster-matte-a2',
    title: 'Matte Poster A2',
    category: 'Posters',
    shortDescription: 'Low-glare matte poster ideal for storefronts, events, and signage boards.',
    priceFrom: 11,
    rating: 4.6,
    reviewsCount: 203,
    tags: ['Bestseller', 'Matte finish'],
    isAvailable: true,
  },
  {
    id: 'poster-gloss-a1',
    title: 'Gloss Poster A1',
    category: 'Posters',
    shortDescription: 'Large glossy posters designed for high-color promotional displays.',
    priceFrom: 15,
    rating: 4.5,
    reviewsCount: 147,
    tags: ['Gloss finish', 'Fast shipping'],
    isAvailable: true,
  },
  {
    id: 'poster-blueprint',
    title: 'Blueprint Technical Poster',
    category: 'Posters',
    shortDescription: 'Precision print output for technical schematics and engineering drawings.',
    priceFrom: 13,
    rating: 4.3,
    reviewsCount: 71,
    tags: ['Most popular', 'Same week'],
    isAvailable: true,
  },
  {
    id: 'poster-photo-large',
    title: 'Large Photo Poster',
    category: 'Posters',
    shortDescription: 'Photo-grade large format posters for interior decoration and exhibitions.',
    priceFrom: 18,
    rating: 4.8,
    reviewsCount: 99,
    tags: ['Premium', 'Gloss finish'],
    isAvailable: true,
  },
  {
    id: 'poster-window-display',
    title: 'Window Display Poster',
    category: 'Posters',
    shortDescription: 'Retail window poster stock engineered for vibrant daylight visibility.',
    priceFrom: 16,
    rating: 4.4,
    reviewsCount: 68,
    tags: ['Fast shipping', 'Bulk discount'],
    isAvailable: false,
  },
  {
    id: 'flyer-economy-a5',
    title: 'Economy Flyer A5',
    category: 'Flyers',
    shortDescription: 'Cost-efficient flyer packs for local campaigns and event promotions.',
    priceFrom: 8,
    rating: 4.2,
    reviewsCount: 286,
    tags: ['Bulk discount', 'Fast shipping'],
    isAvailable: true,
  },
  {
    id: 'flyer-premium-a4',
    title: 'Premium Flyer A4',
    category: 'Flyers',
    shortDescription: 'Heavier stock and cleaner finish for stronger first impression campaigns.',
    priceFrom: 12,
    rating: 4.6,
    reviewsCount: 192,
    tags: ['Bestseller', 'Matte finish'],
    isAvailable: true,
  },
  {
    id: 'flyer-folded-event',
    title: 'Folded Event Flyer',
    category: 'Flyers',
    shortDescription: 'Folded flyer format for event schedules, maps, and agenda communication.',
    priceFrom: 14,
    rating: 4.3,
    reviewsCount: 81,
    tags: ['New', 'Eco'],
    isAvailable: true,
  },
  {
    id: 'flyer-direct-mail',
    title: 'Direct Mail Flyer',
    category: 'Flyers',
    shortDescription: 'Postal-ready flyer sizes with optional address-safe layout zones.',
    priceFrom: 10,
    rating: 4.1,
    reviewsCount: 57,
    tags: ['Same week', 'Bulk discount'],
    isAvailable: true,
  },
  {
    id: 'card-matte-standard',
    title: 'Standard Matte Business Card',
    category: 'Business Cards',
    shortDescription: 'Everyday business cards with balanced color fidelity and crisp edges.',
    priceFrom: 9,
    rating: 4.7,
    reviewsCount: 491,
    tags: ['Bestseller', 'Fast shipping'],
    isAvailable: true,
  },
  {
    id: 'card-soft-touch',
    title: 'Soft Touch Business Card',
    category: 'Business Cards',
    shortDescription: 'Velvet-like lamination for a premium tactile finish and durable surface.',
    priceFrom: 15,
    rating: 4.8,
    reviewsCount: 224,
    tags: ['Premium', 'Most popular'],
    isAvailable: true,
  },
  {
    id: 'card-spot-uv',
    title: 'Spot UV Business Card',
    category: 'Business Cards',
    shortDescription: 'High contrast matte plus gloss accents to emphasize logos and details.',
    priceFrom: 19,
    rating: 4.6,
    reviewsCount: 143,
    tags: ['Gloss finish', 'Premium'],
    isAvailable: true,
  },
  {
    id: 'card-recycled-kraft',
    title: 'Recycled Kraft Business Card',
    category: 'Business Cards',
    shortDescription: 'Sustainable kraft stock with textured finish and minimalist appeal.',
    priceFrom: 11,
    rating: 4.4,
    reviewsCount: 96,
    tags: ['Eco', 'New'],
    isAvailable: false,
  },
  {
    id: 'brochure-trifold-classic',
    title: 'Classic Tri-Fold Brochure',
    category: 'Brochures',
    shortDescription: 'Reliable tri-fold format for product overviews, menus, and company decks.',
    priceFrom: 22,
    rating: 4.5,
    reviewsCount: 176,
    tags: ['Bestseller', 'Bulk discount'],
    isAvailable: true,
  },
  {
    id: 'brochure-zfold-modern',
    title: 'Modern Z-Fold Brochure',
    category: 'Brochures',
    shortDescription: 'Contemporary fold sequence ideal for storytelling and guided messaging.',
    priceFrom: 24,
    rating: 4.4,
    reviewsCount: 122,
    tags: ['Most popular', 'Matte finish'],
    isAvailable: true,
  },
  {
    id: 'brochure-gatefold-premium',
    title: 'Premium Gatefold Brochure',
    category: 'Brochures',
    shortDescription: 'Wide reveal gatefold design suited for launches, events, and premium kits.',
    priceFrom: 31,
    rating: 4.7,
    reviewsCount: 84,
    tags: ['Premium', 'Gloss finish'],
    isAvailable: true,
  },
  {
    id: 'brochure-booklet-8page',
    title: '8-Page Booklet Brochure',
    category: 'Brochures',
    shortDescription: 'Stapled booklet format with extra content space for product details.',
    priceFrom: 34,
    rating: 4.6,
    reviewsCount: 77,
    tags: ['Same week', 'Fast shipping'],
    isAvailable: true,
  },
];
