spring.application.name=eprinting
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/eprinting_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
spring.sql.init.data-locations=classpath:users_dump.sql,classpath:books_dump.sql

security.authentication.mode=jwt
security.jwt.secret=change-me-please-change-me-please-123456789
security.jwt.expiration-seconds=86400
stripe.secret-key=sk_test_51RxSNnRveyiEnQT7zXWwh25ryiBgKOejbSEDd4UOA7B88WPA2qkWdrC3ga63sXDn7QK5Tqm3zmiUfVRATn7oGmnh002ZVOHE1P
stripe.webhook-secret=whsec_cc9305b21a18ddf6e9cfba22f27e75424dc2b837c1fa59f0c6dc236d0e8582c0
stripe.public-key=pk_test_51RxSNnRveyiEnQT7vnZKRvSTi2FQTzPsggIP2SM0EY9bzTbVOHzEIFLbqqNa9ZydgBwXThOGRJxA2dIo2zPEVy6000XVfIDljN