spring.application.name=eprinting
server.port=8080

# Modifiez ces lignes pour utiliser l'utilisateur MySQL du docker-compose
spring.datasource.url=jdbc:mysql://localhost:3306/eprinting_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=eprinting_user
spring.datasource.password=eprinting_pass123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/eprinting

# Client spécifique à valider
keycloak.client-id=eprinting-backend
keycloak.client-secret=your-client-secret  # Pour d'autres types d'interactions

# Validation stricte
keycloak.require-issued-for-client=true
keycloak.strict-audience-validation=true